# Generated by Django 6.0.2 on 2026-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('jd_file', models.FileField(blank=True, upload_to='job')),
                ('resume_folder', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
